language: python

python:
  - "2.7"

sudo: required

install:
  - pip install coveralls

script:
  - bin/test
  - bin/createcoverage

after_success:
  - pip install coverage==3.6 coveralls
  - coveralls
