language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: 46.0.1
env:
  matrix:
    - MASTER=true
    - PENDING_RELEASE=true
matrix:
  allow_failures:
    - env: MASTER=true
  fast_finish: true
install:
  - test $MASTER && sed -ie '/https:\/\/raw\.githubusercontent\.com\/plonegovbr\/portal\.buildout\/master\/buildout\.d\/versions\.cfg/d' buildout.cfg || true
  - python bootstrap-buildout.py
  - bin/buildout annotate
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - ../../bin/code-analysis
  - ../../bin/test
after_script:
  - pkill -9 firefox
after_success:
  - bin/createcoverage -t "--layer=!Acceptance"
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plonegovbr